/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;

import com.github.javafaker.Faker;
import com.google.gson.Gson;
import com.indvd00m.ascii.render.Render;
import com.indvd00m.ascii.render.api.ICanvas;
import com.indvd00m.ascii.render.api.IContextBuilder;
import com.indvd00m.ascii.render.api.IRender;
import com.indvd00m.ascii.render.elements.PseudoText;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());

        IRender render = new Render();
        IContextBuilder builder = render.newBuilder();
        builder.width(80).height(20);
        builder.element(new PseudoText("mosa"));
        ICanvas canvas = render.render(builder.build());
        String s = canvas.getText();
        System.out.println(s);

        // PDF Box
        PDDocument helloPdf = new PDDocument();
        PDPage page = new PDPage(PDRectangle.A4);
        helloPdf.addPage(page);

        PDPageContentStream contentStream = new PDPageContentStream(helloPdf, page);
        contentStream.beginText();
        contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 36);
        contentStream.newLineAtOffset(5, 400);
        contentStream.showText("Hello mosa!!!");
        contentStream.endText();
        contentStream.close();

        helloPdf.save(new File("simple.pdf"));
        helloPdf.close();

        // Code für neue Advanced Dependencies:

        // Java Faker
        Faker faker = new Faker(Locale.forLanguageTag("de"));
        String name = faker.name().fullName();
        String job = faker.job().title();
        String stadt = faker.address().cityName();

        System.out.println("Generierter Test-Nutzer: " + name);
        System.out.println("Beruf: " + job + " in " + stadt);

        // Gson: Doese Datei in ein JSON-Objekt umwandeln
        Gson gson = new Gson();
        Map<String, String> userMap = new HashMap<>();
        userMap.put("name", name);
        userMap.put("job", job);
        userMap.put("city", stadt);

        String jsonOutput = gson.toJson(userMap);
        System.out.println("JSON-Export für API: " + jsonOutput);

    }
}